# Custom Language File for Launcher Customizer

[ejs.app]
title = "Minecraft for Unowhy Crack"

[ejs.landing]
mediaGitHubURL = "https://github.com/biboubaka/MinecraftForUnowhyCrack"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaWebsiteURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/biboubaka/MinecraftForUnowhyCrack"
supportLink = "https://github.com/biboubaka/MinecraftForUnowhyCrack/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR MINECRAFT FOR UNOWHY"
welcomeDescription = "Ce logiciel vous permet de jouer a Minecraft sur votre ordinateur plus facilement car toutes les dépendances sont installées."
welcomeDescCTA = "Vous êtes a quelques clics de jouer a Miceraft."
